name: CI (smoke test)

on:
  push:
  pull_request:

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Smoke test imports
        run: |
          python - <<'PY'
          import sys, importlib
          from pathlib import Path

          # Ensure src/ on path
          sys.path.append(str(Path("src").resolve()))

          # Core third-party deps
          import numpy, pandas, torch, matplotlib, sklearn  # noqa

          # Your modules (should NOT run main on import)
          for m in ("cleaning", "dataset", "model", "evaluate"):
              importlib.import_module(m)

          print("✅ Imports OK")
          PY

      - name: Check CLI --help
        run: |
          python - <<'PY'
          import subprocess, sys
          # --help should print usage and exit 0
          for cmd in [
              ["python", "src/evaluate.py", "--help"],
          ]:
              print("Running:", " ".join(cmd))
              res = subprocess.run(cmd, capture_output=True, text=True)
              print(res.stdout)
              assert res.returncode == 0, res.stderr
          print("✅ CLI help OK")
          PY
          
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install ruff
      - run: ruff check src